## Neural Network: MultiClass Classification from scratch
We will modify the architecture that developed in part A to use it for multiclass classification on **Statlog (Vehicle Silhouettes)** Data Set.

More details on the dataset can be found at: https://archive.ics.uci.edu/ml/datasets/Statlog+%28Vehicle+Silhouettes%29

In [64]:
# Package imports
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd 
from fast_ml.model_development import train_valid_test_split
import sklearn
import sklearn.linear_model
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn import preprocessing
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder


%matplotlib inline

np.random.seed(777)

In [65]:
df = pd.read_csv("Vehicle.csv", header=None)
df.rename(columns = {0:"COMPACTNESS", 1:"CIRCULARITY", 2:"DISTANCE CIRCULARITY", 3:"RADIUS RATIO", 18:"Statlog"},inplace = True)
df.head()

COMPACTNESS  CIRCULARITY  DISTANCE CIRCULARITY  RADIUS RATIO    4   5    6  \
0           95           48                    83           178   72  10  162   
1           91           41                    84           141   57   9  149   
2          104           50                   106           209   66  10  207   
3           93           41                    82           159   63   9  144   
4           85           44                    70           205  103  52  149   

    7   8    9   10   11   12   13  14  15   16   17 Statlog  
0  42  20  159  176  379  184   70   6  16  187  197     van  
1  45  19  143  170  330  158   72   9  14  189  199     van  
2  32  23  158  223  635  220   73  14   9  188  196    saab  
3  46  19  143  160  309  127   63   6  10  199  207     van  
4  45  19  144  241  325  188  127   9  11  180  183     bus

In [66]:
df.Statlog.value_counts()

bus     218
saab    217
opel    212
van     199
Name: Statlog, dtype: int64

In [84]:
# creating instance of one-hot-encoder
enc = OneHotEncoder(handle_unknown='ignore')
# passing bridge-types-cat column (label encoded values of bridge_types)
enc_df = pd.DataFrame(enc.fit_transform(df[['Statlog']]).toarray())

Y = enc_df.to_numpy()
Y

array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       ...,
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [85]:
X = df.drop(['Statlog'], axis='columns')
X = X.to_numpy()
X , X.shape

(array([[ 95,  48,  83, ...,  16, 187, 197],
        [ 91,  41,  84, ...,  14, 189, 199],
        [104,  50, 106, ...,   9, 188, 196],
        ...,
        [106,  54, 101, ...,   4, 187, 201],
        [ 86,  36,  78, ...,  25, 190, 195],
        [ 85,  36,  66, ...,  18, 186, 190]], dtype=int64),
 (846, 18))

In [86]:
train_data, X_rem, train_labels, y_rem = train_test_split(X,Y, train_size=0.7)

In [87]:
valid_data, test_data, valid_labels, test_labels = train_test_split(X_rem,y_rem, test_size=0.5)

In [88]:
valid_data

array([[ 85,  43,  69, ...,   4, 181, 184],
       [ 88,  39,  76, ...,   6, 201, 209],
       [ 85,  47,  75, ...,   7, 182, 191],
       ...,
       [101,  53, 108, ...,  24, 190, 201],
       [ 89,  38,  74, ...,   7, 189, 193],
       [ 89,  36,  72, ...,   1, 187, 192]], dtype=int64)

In [89]:
scaler = preprocessing.StandardScaler().fit(train_data)
train_data = scaler.transform(train_data)
valid_data = scaler.transform(valid_data)
test_data = scaler.transform(test_data)

In [90]:
trainx = train_data.T
trainy = train_labels.T
validx = valid_data.T
validy = valid_labels.T
testx = test_data.T
testy = test_labels.T

In [91]:
trainx.shape, trainy.shape, validx.shape, validy.shape, testx.shape, testy.shape

((18, 592), (4, 592), (18, 127), (4, 127), (18, 127), (4, 127))

In [92]:
X = trainx
Y = trainy

In [93]:
### START CODE HERE ###
shape_X = X.shape
shape_Y = Y.shape
m = shape_X[1]  # training set size
### END CODE HERE ###

print ('No. of training samples: ' + str(m))
print ('Number of features per sample: ' + str(shape_X[0]))

No. of training samples: 592
Number of features per sample: 18


In [94]:
def model_architecture(X, Y):
    """
    Arguments:
    X -- input dataset of shape (input size, number of examples)
    Y -- labels of shape (output size, number of examples)
    
    Returns:
    n_x -- the size of the input layer
    n_h -- the size of the hidden layer
    n_y -- the size of the output layer
    """
    ### START CODE HERE ### 
    n_x = shape_X[0] # size of input layer
    n_h = 10 
    n_y = shape_Y[0] # size of output layer
    ### END CODE HERE ###
    return (n_x, n_h, n_y)

In [95]:
def initialize_parameters(n_x, n_h, n_y):
    """
    Argument:
    n_x -- size of the input layer
    n_h -- size of the hidden layer
    n_y -- size of the output layer
    
    Returns:
    params -- python dictionary containing your parameters:
                    W1 -- weight matrix of shape (n_h, n_x)
                    b1 -- bias vector of shape (n_h, 1)
                    W2 -- weight matrix of shape (n_y, n_h)
                    b2 -- bias vector of shape (n_y, 1)
    """
    
    np.random.seed(2)

    
    ### START CODE HERE ###
    W1 = np.random.randn(n_h, n_x) * 0.01
    b1 = np.zeros((n_h, 1))
    W2 = np.random.randn(n_y, n_h) * 0.01
    b2 = np.zeros((n_y, 1))
    ### END CODE HERE ###
    
    assert (W1.shape == (n_h, n_x))
    assert (b1.shape == (n_h, 1))
    assert (W2.shape == (n_y, n_h))
    assert (b2.shape == (n_y, 1))
    
    parameters = {"W1": W1,
                  "b1": b1,
                  "W2": W2,
                  "b2": b2}
    
    return parameters

In [96]:
def sigmoid(x):
    ### Update THE CODE HERE ###
    return 1/(1 + np.exp(-x))
    ### END CODE HERE ###

In [97]:
def relu(X):
    return np.maximum(0,X)

In [112]:
def softmax(vector):
    e = np.exp(vector)
    return e / e.sum()

In [166]:
def forward_propagation(X, parameters):
    """
    Argument:
    X -- input data of size (n_x, m)
    parameters -- python dictionary containing your parameters (output of initialization function)
    
    Returns:
    A2 -- The sigmoid output of the second activation
    cache -- a dictionary containing "Z1", "A1", "Z2" and "A2"
    """
    # Retrieve each parameter from the dictionary "parameters"
    ### START CODE HERE ### 
    W1 = parameters.get('W1')
    b1 = parameters.get('b1')
    W2 = parameters.get('W2')
    b2 = parameters.get('b2')
    ### END CODE HERE ###
    
    # Implement Forward Propagation to calculate A2 (probabilities)
    ### START CODE HERE ### 
    Z1 = np.dot(W1, X) + b1 
    A1 = np.tanh(Z1)
#     A1 = relu(Z1)
#     A1 = sigmoid(Z1)
    Z2 = np.dot(W2, A1) + b2
    A2 = softmax(Z2)
    ### END CODE HERE ###
    
   
    assert(A2.shape == (4, X.shape[1]))
    
    cache = {"Z1": Z1,
             "A1": A1,
             "Z2": Z2,
             "A2": A2}
    
    return A2, cache

In [167]:
def compute_loss(A2, Y):
    """
    Arguments:
    A2 -- The sigmoid output of the second activation, of shape (1, number of examples)
    Y -- "true" labels vector of shape (1, number of examples)
       
    Returns:
    loss -- cross-entropy loss given equation (7)
    
    """
    
    m = Y.shape[1] # number of example

    # Compute the cross-entropy loss
    ### START CODE HERE ###
    logprobs = np.multiply(np.log(A2),Y) + np.multiply(np.log(1-A2),(1-Y))
    loss = - np.sum(logprobs)
    ### END CODE HERE ###
    
    loss = float(np.squeeze(loss))

    assert(isinstance(loss, float))
    
    return loss

In [168]:
def backprop(parameters, cache, X, Y):
    """
    Arguments:
    parameters -- python dictionary containing our parameters 
    cache -- a dictionary containing "Z1", "A1", "Z2" and "A2".
    X -- input data
    Y -- "true" labels
    
    Returns:
    grads -- python dictionary containing your gradients with respect to different parameters
    """
    m = X.shape[1]
    
    # First, retrieve W1 and W2 from the dictionary "parameters".
    ### START CODE HERE ### 
    W1 = parameters.get('W1')
    W2 = parameters.get('W2')
    ### END CODE HERE ###
        
    # Retrieve also A1 and A2 from dictionary "cache".
    ### START CODE HERE ### 
    A1 = cache.get('A1')
    A2 = cache.get('A2')
    ### END CODE HERE ###
    
    # Backward propagation: calculate dW1, db1, dW2, db2. 
    ### START CODE HERE ### 
    dZ2 = A2 - Y
    dW2 = (1 / m) * np.dot(dZ2, A1.T)
    db2 = (1 / m) * np.sum(dZ2, axis=1, keepdims=True)
    dZ1 = np.dot(W2.T, dZ2) * (1 - np.power(A1, 2))
    dW1 = (1 / m) * np.dot(dZ1, X.T)
    db1 = (1 / m) * np.sum(dZ1, axis=1, keepdims=True)
    ### END CODE HERE ###
    
    grads = {"dW1": dW1,
             "db1": db1,
             "dW2": dW2,
             "db2": db2}
    
    return grads

In [169]:
def update(parameters, grads, learning_rate = 0.01):
    """
    Arguments:
    parameters -- python dictionary containing your parameters 
    grads -- python dictionary containing your gradients 
    learning_rate -- The learning rate
    
    Returns:
    parameters -- python dictionary containing your updated parameters 
    """
    # Retrieve each parameter from the dictionary "parameters"
    ### START CODE HERE ### 
    W1 = parameters.get('W1')
    b1 = parameters.get('b1')
    W2 = parameters.get('W2')
    b2 = parameters.get('b2')
    ### END CODE HERE ###
    
    # Retrieve each gradient from the dictionary "grads"
    ### START CODE HERE ### 
    dW1 = grads.get('dW1')
    db1 = grads.get('db1')
    dW2 = grads.get('dW2')
    db2 = grads.get('db2')
    ## END CODE HERE ###
    
    # Update rule for each parameter
    ### START CODE HERE ### 
    W1 = W1 - learning_rate * dW1
    b1 = b1 - learning_rate * db1
    W2 = W2 - learning_rate * dW2
    b2 = b2 - learning_rate * db2
    ### END CODE HERE ###
    
    parameters = {"W1": W1,
                  "b1": b1,
                  "W2": W2,
                  "b2": b2}
    
    return parameters

In [170]:
def NeuralNetwork(X, Y, n_h, num_iterations = 10000, learning_rate = 0.01, print_loss=False):
    """
    Arguments:
    X -- dataset
    Y -- labels 
    n_h -- size of the hidden layer
    num_iterations -- Number of iterations in gradient descent loop
    learning_rate -- The learning rate
    print_loss -- if True, print the loss every 1000 iterations
    
    Returns:
    parameters -- parameters learnt by the model. They can then be used to make predictions.
    """
    
    np.random.seed(3)
    n_x = model_architecture(X, Y)[0]
    n_y = model_architecture(X, Y)[2]
    
    # Initialize parameters
    ### START CODE HERE ### 
    parameters = initialize_parameters(n_x, n_h, n_y)
    ### END CODE HERE ###
    
    # Loop (gradient descent)

    for i in range(0, num_iterations):
         
        ### START CODE HERE ### 
        # Forward propagation. Inputs: "X, parameters". Outputs: "A2, cache".
        A2, cache = forward_propagation(X, parameters)
        
        # loss function. Inputs: "A2, Y, parameters". Outputs: "loss".
        loss = compute_loss(A2, Y)
 
        # Backpropagation. Inputs: "parameters, cache, X, Y". Outputs: "grads".
        grads = backprop(parameters, cache, X, Y)
 
        # Gradient descent parameter update. Inputs: "parameters, grads". Outputs: "parameters".
        parameters =  update(parameters, grads, learning_rate = 0.01)
        
        ### END CODE HERE ###
        
        # Print the loss every 100 iterations
        if print_loss and i % 100 == 0:
            print ("loss after iteration %i: %f" %(i, loss))

    return parameters

In [204]:
def predict(parameters, X):
    """
    Arguments:
    parameters -- python dictionary containing your parameters 
    X -- input data 
    
    Returns
    predictions -- vector of predictions of our model
    """
    
    # Computes probabilities using forward propagation, and classifies to 0/1 using 0.5 as the threshold.
    ### START CODE HERE ### 
    A2, cache = forward_propagation(X, parameters)
    
    predictions = np.argmax(A2, axis = 0)
    ### END CODE HERE ###
    
    return predictions

In [205]:
# Build a model with a n_h-dimensional hidden layer
parameters = NeuralNetwork(X, Y, 1, num_iterations = 10000, learning_rate = 0.1, print_loss=False)

In [206]:
# Print accuracy
predictions = predict(parameters, X)
print(accuracy_score(np.argmax(Y.T, axis = 1), predictions.T))

0.49324324324324326


In [212]:
# Print accuracy
predictions_validation = predict(parameters, validx)
print(accuracy_score(np.argmax(validy.T, axis = 1), predictions_validation.T))

0.5039370078740157


In [213]:
# Print accuracy
predictions_test = predict(parameters, testx)
print(accuracy_score(np.argmax(testy.T, axis = 1), predictions_test.T))

0.3700787401574803
